books:
	poetry run python data_extraction.py

process:
	poetry run python processing.py --use_spacy --describe

tokens:
	poetry run python tokenizer.py

embeddings:
	poetry run python embeddings.py 


search:
	poetry run python semantic_search.py 
