multi-index:
	poetry run python src/indexing.py --multi_index

single-index:
	poetry run python src/indexing.py --no-multi_index

query-singe-index:
	poetry run python src/similarity_search.py --no-multi_index 

query-dark-days:
	poetry run python src/similarity_search.py --multi_index --book_file_name dark_days

query-africa-unite:
	poetry run python src/similarity_search.py --multi_index --book_file_name africa_unite

query-neocolonialism:
	poetry run python src/similarity_search.py --multi_index --book_file_name neo_colonialism

